import { z } from "zod";

export const DrillItemSchema = z.object({
  prompt: z.string().min(1),
  answer: z.string().min(1)
});

export const RecognitionItemSchema = z.object({
  form: z.string().min(1),
  meaning: z.string().min(1)
});

export const LessonSchema = z.object({
  unit: z.string().min(1),
  phase: z.string().min(1),
  lessonObjectives: z.array(z.string().min(1)).min(1),
  lessonChecklist: z.array(z.string().min(1)).min(1),
  pattern: z.string().min(1),
  verbs: z.array(z.string().min(1)).min(1),
  recognition: z.array(RecognitionItemSchema).default([]),
  conjugation: z.array(DrillItemSchema).default([]),
  sentenceBuilding: z.array(DrillItemSchema).default([]),
  story: z.array(z.string().min(1)).min(1),
  useAutoGeneratedDrills: z.boolean().optional()
});

export type DrillItem = z.infer<typeof DrillItemSchema>;
export type RecognitionItem = z.infer<typeof RecognitionItemSchema>;
export type Lesson = z.infer<typeof LessonSchema>;

export type CurriculumUnit = Lesson & {
  id: string;
  lessonNumber: number;
};

export function validateLesson(lesson: unknown, sourceName: string): Lesson {
  const parsed = LessonSchema.safeParse(lesson);
  if (!parsed.success) {
    const issues = parsed.error.issues
      .map((issue) => `${issue.path.join(".") || "(root)"}: ${issue.message}`)
      .join("; ");
    throw new Error(`Invalid lesson schema for ${sourceName}: ${issues}`);
  }

  return parsed.data;
}
